version: "3.9"

networks:
  etl-manager:
    name: etl-manager
    driver: bridge

services:
  kafka:
    image: apache/kafka:4.1.1
    container_name: kafka
    hostname: kafka
    restart: unless-stopped
    user: root
    networks: [ etl-manager]
    ports:
      - "9082:9092"      # akses dari luar VM: PLAINTEXT
    environment:
      # ====== KRaft (tanpa ZooKeeper) ======
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      
      # ====== Setting single-node yang aman/masuk akal ======
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: "false"

      KAFKA_LOG_DIRS: /var/lib/kafka/data

      # JVM (sesuaikan resource VM)
      KAFKA_HEAP_OPTS: -Xms1g -Xmx1g

    ulimits:
      nofile: { soft: 100000, hard: 100000 }
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list >/dev/null 2>&1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s

  kafka-ui:
    container_name: kafka-ui-cluster
    image: provectuslabs/kafka-ui:latest
    ports:
      - 9070:8080
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka_cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: kafka-connect
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kconnect:8083
      DYNAMIC_CONFIG_ENABLED: 'true'
    restart: unless-stopped
    networks: [etl-manager]

  kconnect:
    container_name: kafka-connect
    image: quay.io/debezium/connect:3.2
    ports:
      - 8083:8083
    environment:
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
      BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_PLUGIN_PATH: "/usr/share/java,/etc/kafka-connect/jars"
    volumes:
      - ./connect-plugins:/etc/kafka-connect/jars
      - ./secrets:/etc/secrets:ro
    depends_on: [kafka]
    networks: [etl-manager]
    restart: unless-stopped

  sequin:
    image: sequin/sequin:latest
    pull_policy: always
    ports:
      - "7376:7376"
    environment:
      - PG_HOSTNAME=sequin_postgres
      - PG_DATABASE=sequin
      - PG_PORT=5432
      - PG_USERNAME=postgres
      - PG_PASSWORD=postgres
      - PG_POOL_SIZE=20
      # Un-comment for SSL
      # - PG_SSL=true
      - SECRET_KEY_BASE=wDPLYus0pvD6qJhKJICO4dauYPXfO/Yl782Zjtpew5qRBDp7CZvbWtQmY0eB13If
      - VAULT_KEY=2Sig69bIpuSm2kv0VQfDekET2qy8qUZGI8v3/h3ASiY=
      - REDIS_URL=redis://sequin_redis:6379
      - CONFIG_FILE_PATH=/config/playground.yml
    volumes:
      - ./playground.yml:/config/playground.yml
    depends_on:
      sequin_redis:
        condition: service_started
      sequin_postgres:
        condition: service_healthy
    networks: [etl-manager]

  sequin_postgres:
    image: postgres:16
    ports:
      - "7377:5432"
    environment:
      - POSTGRES_DB=sequin
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: ["postgres", "-c", "wal_level=logical"]
    volumes:
      - sequin_postgres_data:/var/lib/postgresql/data
      # Creates a sample database for Sequin's Quickstart guide
      - ./postgres-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sequin"]
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 2s
      start_interval: 1s
    networks: [etl-manager]

  sequin_redis:
    image: redis:7
    ports:
      - "7378:6379"
    command: ["redis-server", "--port", "6379"]
    volumes:
      - sequin_redis_data:/data
    networks: [etl-manager]

  sequin_prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9080:9090"
    networks: [etl-manager]

  sequin_grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - sequin_prometheus
    volumes:
      - sequin_grafana_data:/var/lib/grafana
      - ./grafana_datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana_dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./dashboard.json:/etc/grafana/dashboards/dashboards/sequin.json
    networks: [etl-manager]

  postgres-source:
    image: postgres:17
    container_name: postgres_cdc
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres # Ganti dengan password yang aman
      POSTGRES_DB: postgres
    ports:
      - "5532:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Command ini yang mengaktifkan fitur CDC
    command: >
      postgres 
      -c wal_level=logical 
      -c max_replication_slots=10 
      -c max_wal_senders=10
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks: [etl-manager]

volumes:
  sequin_postgres_data:
  sequin_redis_data:
  sequin_grafana_data:
  kafka-data:
  postgres_data:
